color0 #41484b
color1 #ffb4ab
color2 #9ecee2
color3 #b7c9d2
color4 #dbbce7
color5 #9ecee2
color6 #b7c9d2
color7 #e2e2e4
color8 #8a9296
color9 #ffb4ab
color10 #9ecee2
color11 #b7c9d2
color12 #dbbce7
color13 #9ecee2
color14 #b7c9d2
color15 #e2e2e4

cursor                #e2e2e4
cursor_text_color     #111415
background            #111415
foreground            #e2e2e4
selection_foreground  #c0c8cc
selection_background  #41484b
active_border_color   #9ecee2
inactive_border_color #41484b
url_color             #9ecee2

active_tab_foreground   #003544
active_tab_background   #9ecee2
inactive_tab_foreground #c0c8cc
inactive_tab_background #41484b
cursor_trail_color      #c0c8cc
