color0 #424849
color1 #ffb4ab
color2 #e0f9fc
color3 #bfc8c9
color4 #f8f1ff
color5 #b3cbce
color6 #bfc8c9
color7 #e3e2e2
color8 #8c9292
color9 #ffb4ab
color10 #e0f9fc
color11 #bfc8c9
color12 #f8f1ff
color13 #b3cbce
color14 #bfc8c9
color15 #e3e2e2

cursor                #e3e2e2
cursor_text_color     #121414
background            #121414
foreground            #e3e2e2
selection_foreground  #c2c8c8
selection_background  #424849
active_border_color   #e0f9fc
inactive_border_color #424849
url_color             #e0f9fc

active_tab_foreground   #1e3436
active_tab_background   #e0f9fc
inactive_tab_foreground #c2c8c8
inactive_tab_background #424849
cursor_trail_color      #c2c8c8
