[FileDialog]
history=file:///run/media/ghost/MEDIA-2/%5BAnime Time%5D One Piece (0001-1071+Movies+Specials) %5BBD+CR%5D %5BDual Audio%5D %5B1080p%5D%5BHEVC 10bit x265%5D%5BAAC%5D%5BMulti Sub%5D, file:///run/media/ghost/MEDIA-2, file:///home/ghost
lastVisited=file:///home/ghost
qtVersion=6.11.2
shortcuts=file:, file:///home/ghost
sidebarWidth=95
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)"
viewMode=Detail
